### ISSUE TITLE
Error in matrix(0, n - 1, n - 1) : invalid 'nrow' value (too large or NA)

### ISSUE THREAD

**Issue by QianChwnLyn** [dmcable/spacexr#124]
hello, when I run run.RCTD function,  I met this error.
“_myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')

fitBulk: decomposing bulk
chooseSigma: using initial Q_mat with sigma =  1
Error in matrix(0, n - 1, n - 1) : invalid 'nrow' value (too large or NA)_”

Then, I checked run.RCTD function, this error came from _"choose_sigma_c"_ function. 
<img width="603" alt="WechatIMG42232" src="https://user-images.githubusercontent.com/102777768/207547616-c15119e8-f072-4e7b-ba80-ac24d562c6c2.png">

I run this function step by step until "_for (iter in 1:myRCTD@config$N_epoch) {
    set_likelihood_vars(Q_mat_all[[as.character(sigma)]], 
                        X_vals)_".
And this error occured. 
"_Error in matrix(0, n - 1, n - 1) : invalid 'nrow' value (too large or NA)_"

So maybe you can help with this? Thanks.

**Comment by QianChwnLyn** [comment]
This version is 2.1.0. I installed previous version, and no this error.

**Comment by dmcable** [comment]
Thanks, this should be fixed now. Please let me know if there are any other issues with the recent update.

**Comment by boyiguo1** [comment]
Thanks for your prompt response. The previously mentioned problem seems to resolved when I replicated the tutorial.
> Error in matrix(0, n - 1, n - 1) : invalid 'nrow' value (too large or NA)

Nevertheless, I am having a new problem with the new submit [e8603fa](https://github.com/dmcable/spacexr/commit/e8603fa05a3b46e08ca8f90fad63035ef172552a) when running parallel. 

When running the following code
```
set.seed(1)
myRCTD <- create.RCTD(puck, reference, max_cores = 2)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')
```
I am encountering an error reporting `"object 'SQ_mat' not found"`.
> fitBulk: decomposing bulk
chooseSigma: using initial Q_mat with sigma =  1
starting worker pid=6723 on localhost:11719 at 10:52:38.668
starting worker pid=6737 on localhost:11719 at 10:52:38.908
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Error in { : task 1 failed - "object 'SQ_mat' not found"

The same error didn't happen when specifying `max_cores = 1`

**Comment by dmcable** [comment]
Thanks; I believe this issue should be fixed now.

**Comment by boyiguo1** [comment]
Thank you for your prompt fix. But unfortunately, the problem seems still persists with commit c3091650.

Wiredly, the error was triggered after multiple iterations of sigma values. (I tested both 2 and 3 for `max_cores`)

```
set.seed(1)
myRCTD <- create.RCTD(puck, reference, max_cores = 3)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')
```

>> myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')
fitBulk: decomposing bulk
chooseSigma: using initial Q_mat with sigma =  1
starting worker pid=7518 on localhost:11173 at 11:22:25.788
starting worker pid=7532 on localhost:11173 at 11:22:26.049
starting worker pid=7546 on localhost:11173 at 11:22:26.308
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Likelihood value: 1970.41846749908
Sigma value:  0.84
starting worker pid=7567 on localhost:11173 at 11:22:31.366
starting worker pid=7581 on localhost:11173 at 11:22:31.597
starting worker pid=7595 on localhost:11173 at 11:22:31.830
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Likelihood value: 1964.4988387465
Sigma value:  0.84
starting worker pid=7616 on localhost:11173 at 11:22:36.566
starting worker pid=7630 on localhost:11173 at 11:22:36.799
starting worker pid=7644 on localhost:11173 at 11:22:37.035
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Loading required package: spacexr
loaded spacexr and set parent environment
Error in { : task 1 failed - "object 'SQ_mat' not found"

**Comment by boyiguo1** [comment]
Also, compared to the results running single core. The algorithm should have stopped. 

The following are the results from running `max.cores = 1`
> fitBulk: decomposing bulk
chooseSigma: using initial Q_mat with sigma =  1
Likelihood value: 1970.41846749908
Sigma value:  0.84
Likelihood value: 1964.4988387465
Sigma value:  0.84

**Comment by dmcable** [comment]
Apologies, missed one line I was supposed to change. It is fixed now.

**Comment by boyiguo1** [comment]
Also, just reporting back. I don't have any errors when replicating the RCTD tutorial using multiple cores with the version 2.1.3. Thank you.

Nevertheless, I am having an error relates to `Q_mat_all` when running `run.CSIDE` as one of the downstream steps. specifically, when I run 
```
barcodes <- intersect(names(myRCTD@spatialRNA@nUMI), colnames(myRCTD@spatialRNA@counts))
X <- as.matrix(rep(1, length(barcodes)))
rownames(X) <- barcodes

myRCTD <- run.CSIDE(myRCTD, X, barcodes, gene_threshold = .001, 
                    cell_type_threshold = 5, fdr = 0.25)
```

I have 
> run.CSIDE.general: running CSIDE with cell types 10, 18
run.CSIDE.general: configure params_to_test = 1, 
filter_genes: filtering genes based on threshold = 0.001
set_global_Q_all: begin
set_global_Q_all: finished
**Error in Q_mat_all[[sigma]] : invalid subscript type 'closure'**
In addition: Warning message:
In run.CSIDE.general(myRCTD, X1, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold,  :
  run.CSIDE.general: some parameters are set to the CSIDE vignette values, which are intended for testing but not proper execution. For more accurate results, consider using the default parameters to this function.


I wonder if this is related to the recent fixes you made. Thanks!

**Comment by dmcable** [comment]
Thanks for catching all of these errors! I just fixed the relevant typo. This new version should make C-SIDE substantially faster.

**Comment by boyiguo1** [comment]
Thanks for fixing these.

Just some feedback:
- When running `run.CSIDE` with 1 core, I am having a lot of genes as the output. I am not sure if this is intended. 
>run.CSIDE.general: running CSIDE with cell types 10, 18
run.CSIDE.general: configure params_to_test = 1, 
filter_genes: filtering genes based on threshold = 0.001
set_global_Q_all: begin
set_global_Q_all: finished
1
[1] "Xkr4"
2
[1] "Rims1"
3
[1] "Adgrb3"

- When running `run.CSIDE` with multiple cores, I encountered the following error. 
>run.CSIDE.general: running CSIDE with cell types 10, 18
run.CSIDE.general: configure params_to_test = 1, 
filter_genes: filtering genes based on threshold = 0.001
set_global_Q_all: begin
set_global_Q_all: finished
starting worker pid=10786 on localhost:11689 at 18:53:08.169
starting worker pid=10800 on localhost:11689 at 18:53:08.434
starting worker pid=10820 on localhost:11689 at 18:53:08.761
starting worker pid=10834 on localhost:11689 at 18:53:09.004
starting worker pid=10848 on localhost:11689 at 18:53:09.242
**Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  unable to find variable "calc_Q_k"**
  
  
  Thanks!

**Comment by dmcable** [comment]
Thank you, these issues have been fixed!

**Comment by boyiguo1** [comment]
All the previously reported problems seem to be resolved. Thank you!
