### ISSUE TITLE
run.CSIDE.single with full/multi doublet mode 

### ISSUE THREAD

**Issue by jana-rajova** [dmcable/spacexr#142]
I get the following error when running CSIDE on both my data and the "visium_CSIDE_celltocell_interactions.Rmd", I get the following message.

Error in if (myRCTD@config$doublet_mode == "multi") { : 
  argument is of length zero

My session info:
```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.1      SeuratObject_4.1.3 Seurat_4.3.0       anndata_0.7.5.5    Matrix_1.5-3       spacexr_2.2.0     

loaded via a namespace (and not attached):
  [1] Rtsne_0.16             colorspace_2.1-0       deldir_1.0-6           ellipsis_0.3.2         ggridges_0.5.4         rprojroot_2.0.3        rstudioapi_0.14        spatstat.data_3.0-0    farver_2.1.1          
 [10] leiden_0.4.3           listenv_0.9.0          ggrepel_0.9.3          fansi_1.0.4            codetools_0.2-18       splines_4.2.2          doParallel_1.0.17      knitr_1.42             polyclip_1.10-4       
 [19] jsonlite_1.8.4         ica_1.0-3              cluster_2.1.4          png_0.1-8              uwot_0.1.14            shiny_1.7.4            sctransform_0.3.5      spatstat.sparse_3.0-0  compiler_4.2.2        
 [28] httr_1.4.4             assertthat_0.2.1       fastmap_1.1.0          lazyeval_0.2.2         cli_3.6.0              later_1.3.0            htmltools_0.5.4        tools_4.2.2            igraph_1.4.0          
 [37] gtable_0.3.1           glue_1.6.2             RANN_2.6.1             reshape2_1.4.4         dplyr_1.1.0            rappdirs_0.3.3         Rcpp_1.0.10            scattermore_0.8        vctrs_0.5.2           
 [46] nlme_3.1-160           spatstat.explore_3.0-6 progressr_0.13.0       iterators_1.0.14       lmtest_0.9-40          spatstat.random_3.1-3  xfun_0.37              stringr_1.5.0          globals_0.16.2        
 [55] mime_0.12              miniUI_0.1.1.1         lifecycle_1.0.3        irlba_2.3.5.1          goftest_1.2-3          future_1.31.0          MASS_7.3-58.1          zoo_1.8-11             scales_1.2.1          
 [64] promises_1.2.0.1       spatstat.utils_3.0-1   parallel_4.2.2         rematch2_2.1.2         RColorBrewer_1.1-3     prismatic_1.1.1        yaml_2.3.7             reticulate_1.28        pbapply_1.7-0         
 [73] gridExtra_2.3          stringi_1.7.12         paletteer_1.5.0        foreach_1.5.2          rlang_1.0.6            pkgconfig_2.0.3        matrixStats_0.63.0     evaluate_0.20          lattice_0.20-45       
 [82] ROCR_1.0-11            purrr_1.0.1            tensor_1.5             labeling_0.4.2         patchwork_1.1.2        htmlwidgets_1.6.1      cowplot_1.1.1          tidyselect_1.2.0       here_1.0.1            
 [91] parallelly_1.34.0      RcppAnnoy_0.0.20       plyr_1.8.8             magrittr_2.0.3         R6_2.5.1               generics_0.1.3         withr_2.5.0            pillar_1.8.1           fitdistrplus_1.1-8    
[100] survival_3.4-0         abind_1.4-5            sp_1.6-0               tibble_3.1.8           future.apply_1.10.0    KernSmooth_2.23-20     utf8_1.2.3             spatstat.geom_3.0-6    plotly_4.10.1         
[109] rmarkdown_2.20         grid_4.2.2             data.table_1.14.6      digest_0.6.31          xtable_1.8-4           tidyr_1.3.0            httpuv_1.6.8           munsell_0.5.0          viridisLite_0.4.1    
```

**Comment by jana-rajova** [comment]
My bad, the RCTD now names it "RCTDmode" instead of "doublet_mode"

fixed with
```
myRCTD@config$doublet_mode = myRCTD@config$RCTDmode
```

**Comment by krademaker** [comment]
@dmcable Could this issue be re-opened?

I was following the vignette [Multiple regions in Visium with full mode RCTD](https://raw.githack.com/dmcable/spacexr/master/vignettes/visium_full_regions.html) and encountered the same error when running:
```
myRCTD@config$max_cores <- 8
myRCTD <- run.CSIDE.regions(myRCTD, region_list,cell_types = cell_types, gene_threshold = .01, cell_type_threshold = 10, fdr = 0.25, doublet_mode = F, weight_threshold = 0.1)
```
With this output:
```
Warning message in run.CSIDE.general(myRCTD, X1, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold, :
“run.CSIDE.general: some parameters are set to the CSIDE vignette values, which are intended for testing but not proper execution. For more accurate results, consider using the default parameters to this function.”

Error in if (myRCTD@config$doublet_mode == "multi") {: argument is of length zero
Traceback:

1. run.CSIDE.regions(myRCTD, region_list, cell_types = cell_types, 
 .     gene_threshold = 0.01, cell_type_threshold = 10, fdr = 0.25, 
 .     doublet_mode = F, weight_threshold = 0.1)
2. run.CSIDE(myRCTD, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold, 
 .     gene_threshold = gene_threshold, doublet_mode = doublet_mode, 
 .     test_mode = "categorical", weight_threshold = weight_threshold, 
 .     sigma_gene = sigma_gene, params_to_test = 1:dim(X2)[2], PRECISION.THRESHOLD = PRECISION.THRESHOLD, 
 .     test_genes_sig = test_genes_sig, cell_types_present = cell_types_present, 
 .     fdr = fdr, normalize_expr = F, logs = logs, log_fc_thresh = log_fc_thresh, 
 .     test_error = test_error)
3. run.CSIDE.general(myRCTD, X1, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold, 
 .     gene_threshold = gene_threshold, doublet_mode = doublet_mode, 
 .     test_mode = test_mode, weight_threshold = weight_threshold, 
 .     sigma_gene = sigma_gene, PRECISION.THRESHOLD = PRECISION.THRESHOLD, 
 .     params_to_test = params_to_test, cell_types_present = cell_types_present, 
 .     test_genes_sig = test_genes_sig, fdr = fdr, normalize_expr = normalize_expr, 
 .     logs = logs, cell_type_filter = cell_type_filter, log_fc_thresh = log_fc_thresh, 
 .     test_error = test_error, fdr_method = fdr_method)
```
Double-checking the variable
```
myRCTD@config$doublet_mode
NULL
```

`myRCTD@config$doublet_mode = myRCTD@config$RCTDmode` as suggested [above](https://github.com/dmcable/spacexr/issues/142#issuecomment-1445371082) is a work-around, but it doesn't address the original issue.

It appears that `run.CSIDE.general` addresses `myRCTD@config$doublet_mode` and `myRCTD@config$RCTDmode` variables, but in the if-evaluation an error is thrown [on this line](https://github.com/dmcable/spacexr/blob/205c9acdcd5b9b794ae0521ab50473893e9e887f/R/CSIDE.R#L293) because the `myRCTD@config$doublet_mode` variable doesn't exist.

**Comment by dmcable** [comment]
Hi, thanks for pointing out this error. I have replaced `config$doublet_mode` with `config$RCTDmode`, and I believe this should fix the issue. Let me know if there is anything else.

Dylan

**Comment by krademaker** [comment]
Hi Dylan,

Thank you for looking into it and fixing it. If any other issues persists I will let you know.

Best,
Koen
